"""initial schema

Revision ID: e7790b02be17
Revises: 
Create Date: 2026-09-26 22:16:14.076184
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e7790b02be17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('current_level', sa.Enum('beginner', 'intermediate', 'advanced', name='learner_level'), nullable=False),
    sa.Column('learning_goal', sa.Enum('academic', 'placement', 'interview', 'project', 'general', name='learning_goal'), nullable=False),
    sa.Column('hours_per_week', sa.Float(), nullable=False),
    sa.Column('target_duration', sa.Integer(), nullable=False),
    sa.Column('estimated_level', sa.Enum('beginner', 'intermediate', 'advanced', name='estimated_level'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learners_topic'), 'learners', ['topic'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('strong_topics', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('weak_topics', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_learner_id'), 'assessments', ['learner_id'], unique=False)
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('mastery_level', sa.Enum('beginner', 'intermediate', 'advanced', name='mastery_level'), nullable=False),
    sa.Column('last_score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'topic', name='uq_progress_learner_topic')
    )
    op.create_index(op.f('ix_progress_learner_id'), 'progress', ['learner_id'], unique=False)
    op.create_index(op.f('ix_progress_topic'), 'progress', ['topic'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='quiz_difficulty'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_learner_id'), 'quiz_attempts', ['learner_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_topic'), 'quiz_attempts', ['topic'], unique=False)
    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('roadmap_data', sa.JSON(), nullable=False),
    sa.Column('focus_areas', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_learner_id'), 'roadmaps', ['learner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmaps_learner_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index(op.f('ix_quiz_attempts_topic'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_learner_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_progress_topic'), table_name='progress')
    op.drop_index(op.f('ix_progress_learner_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_index(op.f('ix_assessments_learner_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_learners_topic'), table_name='learners')
    op.drop_table('learners')
    # ### end Alembic commands ###
